version: '3'

services:
    php:
        build: ./docker/php/${PHP_VERSION}
        container_name: ${DOCKER_NAME}_php
        volumes:
            - ./app:/var/www
            # - ./logs/php:/var/log/php:ro
            # Use for debug config:
            # - ./docker/php/conf.d:/etc/php/7.4/fpm/conf.d
        #environment:
        #    PHP_IDE_CONFIG: "serverName=Docker"
        ports:
            - "9000:9000"
            - "25:25"
        links:
            - db
        extra_hosts:
            - ${APP_DOMAIN}:${NETWORK_INTERFACE}
        networks:
            - default

    web:
        build: ./docker/nginx
        container_name: ${DOCKER_NAME}_web
        volumes:
            - ./app:/var/www:ro
            # - ./logs/nginx:/var/log/nginx:ro
            # Use for debug config:
            # - ./docker/nginx/conf.d:/etc/nginx/conf.d
        environment:
            APP_DOMAIN: ${APP_DOMAIN}
        ports:
            - "80:80"
        links:
            - php
        networks:
            default:
                ipv4_address: ${NETWORK_INTERFACE}

    db:
        build: ./docker/db/${DB_VERSION}
        container_name: ${DOCKER_NAME}_db
        command: ["--default-authentication-plugin=mysql_native_password"]
        volumes:
            - ${DB_PATH}:/var/lib/${DB_CONNECTION}
            # - ./logs/db:/var/log/mysql:ro
            - ./app/backup:/var/www/app/backup
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        networks:
            - default

#    memcached:
#        image: 'memcached'

    mailhog:
        image: mailhog/mailhog
        container_name: ${DOCKER_NAME}_mailhog
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - default

networks:
    default:
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}
